version: "3.8"

services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=meli-bc
      - DB_USERNAME=meli-bc-user
      - DB_PASSWORD=meli-bc-password
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    platform: linux/amd64
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: meli-bc-user
      POSTGRES_PASSWORD: meli-bc-password
      POSTGRES_DB: meli-bc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meli-bc-user -d meli-bc"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: