version: "3.8"
services:
  dcs-postgres:
    image: postgres:15-alpine
    container_name: dcs-postgres
    restart: always
    environment:
      POSTGRES_USER: meli-bc-user
      POSTGRES_PASSWORD: meli-bc-password
      POSTGRES_DB: meli-bc
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  default:
    name: local-network